name: PL/SQL CICD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Oracle Client
        run: |
          sudo apt-get update
          sudo apt-get install -y oracle-instantclient19.8-basic

      - name: Run PL/SQL Tests
        run: |
          sqlplus username/password@hostname:port/SID <<EOF
          @sql/plsql_procedures.sql
          EXIT;
          EOF
