CREATE TABLE Customers (
    Customer_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Email_Office VARCHAR2(100),
    Email_Personal VARCHAR2(100),
    Family_Members CLOB
);

CREATE TABLE Products (
    Product_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Book_Title VARCHAR2(100) NOT NULL,
    Book_Price NUMBER(10, 2) NOT NULL CHECK (Book_Price > 0),
    Book_Quantity NUMBER DEFAULT 0 CHECK (Book_Quantity >= 0)
);

ALTER TABLE Products ADD CONSTRAINT fk_customer FOREIGN KEY (Customer_ID) REFERENCES Customers (Customer_ID);
